### ISSUE TITLE
Ignore empty alt-attributes

### ISSUE THREAD

**Issue by herschel666** [ParhamP/altify#3]
Hi.

Setting the alt-attribute to an empty string is a valid way of indicating that the image is only serving presentational means and is no part of the content. Thus it would imho make more sense having altify ignore those images.

(https://developer.mozilla.org/de/docs/Web/HTML/Element/img#attr-alt)

Best regards.

**Comment by ParhamP** [comment]
HI,
Thank you for the heads up! I will change the program to comply with that.
